icons_format = "{icon}"

[theme]
[theme.overrides]
separator = " "

[icons]
icons = "awesome"

# docker
[[block]]
block = "docker"
interval = 2
format = "{$icon}$running/$total"

# monitors
[[block]]
block = "custom"
command = "xrandr --listmonitors | tail -n+2 | tr '+' ' ' | cut -d' ' -f 4 | tr '\n' ' '"
interval = "once"
signal = 4


# screenshot
[[block]]
block = "custom"
interval = "once"
command = "echo \uf030 scr" # assumes fontawesome icons

[[block.click]]
button = "left"
cmd = "/usr/bin/bash ~/Pictures/ss.sh"


# disk
[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{$icon}FS: $available.eng(2)"

[[block.click]]
button = "left"
update = true
cmd = "nautilus"


# memory
[[block]]
block = "memory"
display_type = "memory"
format_mem = "{$icon}$mem_avail.eng(2)/$mem_total.eng(2)"
format_swap = "{$icon}$swap_used_percents.eng(2)"


# cpu
[[block]]
block = "cpu"
interval = 1
format = "{$icon}$barchart.str() $utilization.eng()"
format_alt = "{$icon}$frequency.eng() \\|$boost.str()"


# load
[[block]]
block = "load"
format = "{$icon}5m: $5m.eng(3)"
interval = 5


# bluetooth
[[block]]
block = "bluetooth"
mac = "B0:F1:A3:76:50:F4" # fill CC2
format = "{$icon}$name"


[[block]]
block = "toggle"
command_state = "if [[ -d /proc/sys/net/ipv4/conf/tun0 ]]; then echo 1; else echo ''; fi"
command_on = "nmcli connection up vpn-VNPT && sudo ifconfig wlp0s20f3 mtu 1250"
command_off = "nmcli connection down vpn-VNPT"
interval = 5
format="{$icon} VNPT"


[[block]]
block = "toggle"
command_state = "if [[ -d /proc/sys/net/ipv4/conf/wg0 ]]; then echo 1; else echo ''; fi"
command_on = "sudo wg-quick up wg0"
command_off = "sudo wg-quick down wg0"
interval = 5
format="{$icon} WG"



## network
[[block]]
device = "wlp0s20f3"
block = "net"
format = "{$icon}{$signal_strength $ssid|Wired connection}"
format_alt = "{$icon}s$speed_down.eng(3,B,K) $speed_up.eng(3,B,K)"

# sound
[[block]]
block = "sound"

# battery
[[block]]
block = "battery"
format = " $icon $percentage "

# time
[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"


# power button
[[block]]
block = "custom"
interval = "once"
command = "echo PWR \uf011" # assumes fontawesome icons

[[block.click]]
button = "left"
cmd = "systemctl `echo 'suspend\npoweroff\nreboot' | dmenu`"

